[[headers]]
for = "/*.js"
  [headers.values]
  Content-Encoding = "br"
  Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.css"
  [headers.values]
  Content-Encoding = "br"
  Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.html"
  [headers.values]
  Content-Encoding = "br"
  Cache-Control = "public, max-age=600"