[[headers]]
for = "/*.js"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Vary = "Accept-Encoding"

[[headers]]
for = "/*.css"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Vary = "Accept-Encoding"

[[headers]]
for = "/*.html"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Vary = "Accept-Encoding"

